ORG 1000H
MSJ1 DB "INGRESE EL PRIMER DIGITO"
FIN1 DB ?
MSJ2 DB "INGRESE EL SEGUNDO DIGITO"
FIN2 DB ?
MSJRES DB "RESULTADO: "
FINRES DB ?
NUM1 DB ?
NUM2 DB ?
RES DB ?
FINRESDW DB ?
NEGATIVESIGN DB "-"
RESNEG DB ?
FINNEGSIGN DB ?
ORG 2000H
MOV BX, OFFSET  MSJ1
MOV AL, OFFSET FIN1-OFFSET MSJ1
INT 7
MOV BX, OFFSET NUM1
INT 6
MOV AL, 1
INT 7
MOV DL, NUM1
XOR AX, AX
XOR BX, BX
MOV BX, OFFSET  MSJ2
MOV AL, OFFSET FIN2-OFFSET MSJ2
INT 7
MOV BX, OFFSET NUM2
INT 6
MOV AL, 1
INT 7
MOV DH, NUM2
XOR AX, AX
XOR BX, BX
MOV BX, OFFSET  MSJRES
MOV AL, OFFSET FINRES-OFFSET MSJRES
INT 7
CMP DL, DH
JS isNegative
JMP notNegative
isNegative: MOV RESNEG, DH
            SUB RESNEG, DL
            ADD RESNEG, 30H
            MOV BX, OFFSET NEGATIVESIGN
            MOV AL, OFFSET FINNEGSIGN-OFFSET NEGATIVESIGN
            INT 7
            JMP endCondition
notNegative: MOV RES, DL
             SUB RES, DH
             ADD RES, 30H
             MOV BX, OFFSET RES
             MOV AL ,OFFSET FINRESDW-OFFSET RES
             INT 7
             JMP endCondition
endCondition: INT 0             
END
;MOV BX, OFFSET NUM1
;MOV BX, OFFSET  MSJ2
;MOV AL, OFFSET FIN-OFFSET MSJ2
;INT 7
;MOV BX, OFFSET NUM2
;INT 6
;MOV AL, 1
;INT 7
;AND NUM1, 0FH
;MOV DL, NUM1
;INT 0
;AND NUM2, 0FH
;MOV DL, NUM2